/domabot/usb_cam:
  ros__parameters:
    auto_white_balance: true
    autoexposure: true
    autofocus: false
    av_device_format: YUV422P
    brightness: 50
    camera_info_url: ''
    camera_name: domabot_image_cam
    contrast: -1
    exposure: 100
    focus: -1
    frame_id: domabot_image_cam
    framerate: 10.0
    gain: -1
    image_height: 720
    image_raw:
      enable_pub_plugins:
      #- image_transport/compressedDepth
      #- image_transport/compressed
      - image_transport/raw
      #- image_transport/theora
      format: jpeg
      jpeg_quality: 95
      png_level: 3
      tiff:
        res_unit: inch
        xdpi: -1
        ydpi: -1
    image_width: 1280
    io_method: mmap
    pixel_format: yuyv
    saturation: -1
    sharpness: -1
    video_device: /dev/video0
    white_balance: 4000

